name: Update Profile Index

on:
  workflow_dispatch:

jobs:
  update:
    uses: assforge/gitflow-packages/.github/workflows/update-org-profile.yml@main
    with:
      org_name: asshive
      org_emoji: "🐝"
      org_title: "Service Hive"
      org_subtitle: "Microsb Platform Microservices"
      section_title: "Services"
    secrets:
      ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
