name: Update Profile Index

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout GitFlow Actions
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.GITFLOW_REPO }}
          ref: main
          token: ${{ secrets.GITFLOW_TOKEN }}
          path: gitflow-actions

      - name: Update Organization Profile
        uses: ./gitflow-actions/actions/update-org-profile
        with:
          org-name: "asshive"
          org-emoji: "🐝"
          org-title: "Service Hive"
          org-subtitle: "Microsb Platform Microservices"
          section-title: "Services"
          org-read-token: ${{ secrets.GITFLOW_TOKEN }}
